// auth
export const SET_LOADING = 'SET_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// user
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

// post
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_USER_POST_BY_ID = 'GET_USER_POST_BY_ID';
export const POSTS_ERROR = 'POSTS_ERROR';
export const ADD_POST_ERROR = "ADD_POST_ERROR" ;
export const DELETE_POST_ERROR = "DELETE_POST_ERROR" ;
export const USER_POSTS_ERROR = "USER_POSTS_ERROR" ;
export const SET_LOADING_ADD_POST = 'SET_LOADING_ADD_POST';
export const SET_LOADING_POSTS = 'SET_LOADING_POSTS';
export const SET_LOADING_USER_POSTS = 'SET_LOADING_USER_POSTS';
export const SET_LOADING_DELETE_POST = 'SET_LOADING_DELETE_POST';

// messages 
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGE_BY_ID = 'GET_MESSAGE_BY_ID';
export const MESSAGES_ERROR = 'MESSAGES_ERROR';
export const SET_LOADING_SEND_MESSAGE = 'SET_LOADING_SEND_MESSAGE';
export const SET_LOADING_MESSAGES = 'SET_LOADING_MESSAGES';


